Configre coredumps + adapt debugging mechanisms
gyroidos/meta-trustx pull request #226
Opened 2024-05-27 13:01 UTC by k0ch4lo

2024-07-01 11:35 UTC, jwsbck commented on recipes-initscripts/cml-boot/cml-boot_1.0.bb
> +		bbwarn "Patching /init script to mount external data fs for debugging purposes"
perhaps add half a sentence in the description above, so this is not only sshd anymore?

2024-07-01 11:39 UTC, jwsbck commented on images/trustx-cml-initramfs.bb
> +	echo 'LABEL=containers     /data/cml/containers ext4       nosuid,nodev,noexec,nofail 0  0' >> ${IMAGE_ROOTFS}/etc/fstab
consistent indentation

2024-07-01 11:39 UTC, jwsbck requested changes
only nitpicking

2024-07-04 05:10 UTC, k0ch4lo commented on images/trustx-cml-initramfs.bb
> +	echo 'LABEL=containers     /data/cml/containers ext4       nosuid,nodev,noexec,nofail 0  0' >> ${IMAGE_ROOTFS}/etc/fstab
change whitespace to tabs consistently

2024-07-04 05:13 UTC, k0ch4lo commented on recipes-initscripts/cml-boot/cml-boot_1.0.bb
> +		bbwarn "Patching /init script to mount external data fs for debugging purposes"
adapted the comment reflecting the changes

2024-07-08 07:14 UTC, jwsbck approved these changes

2024-07-09 04:30 UTC, merged